<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_NAM_lazyloaded</name>
   <tag></tag>
   <elementGuidId>dd5f46e7-ed77-4b2a-bb29-4bc29c645974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt=&quot;Women's homepage&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Women's homepage&quot;] > picture > img.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Women's homepage NỮ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>714578c8-559d-4f8c-bbc6-36672d945ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>19c0c697-ae7f-49ae-9a8c-fbca924cf081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>843beb2e-4bac-427e-aaf2-3429dbf111ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> lazyloaded</value>
      <webElementGuid>f84cace8-c1ec-4a10-bd41-8c25ac76ea57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://file.hstatic.net/1000284478/file/desktop__1__f580965a4cc442b69e614a65d72dde66.jpg</value>
      <webElementGuid>815c05ab-ac57-4f49-b5e1-ef31d4bf2a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Women's homepage</value>
      <webElementGuid>7bf4c068-e76f-4862-bcf4-0c9fc7a8d08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://file.hstatic.net/1000284478/file/desktop__1__f580965a4cc442b69e614a65d72dde66.jpg</value>
      <webElementGuid>62b9e23a-e459-496a-9442-7a292e5a976f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;Page_index&quot;]/main[@class=&quot;wrapper-main-body index-content&quot;]/div[@class=&quot;section-home-page&quot;]/div[@class=&quot;wrapper-gender-banner&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;inner-gender-banner&quot;]/div[@class=&quot;item-banner-gender&quot;]/a[1]/picture[1]/img[@class=&quot;lazyloaded&quot;]</value>
      <webElementGuid>82d8a14a-595f-49f4-a4ec-2ca50c545733</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=&quot;Women's homepage&quot;]</value>
      <webElementGuid>0c7c5377-0c44-48cf-b8af-f9b6777f28b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/picture/img</value>
      <webElementGuid>588a3adc-a631-4ef3-bce5-e090d4bad8fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = concat(&quot;Women&quot; , &quot;'&quot; , &quot;s homepage&quot;) and @src = 'https://file.hstatic.net/1000284478/file/desktop__1__f580965a4cc442b69e614a65d72dde66.jpg']</value>
      <webElementGuid>b5fec16a-b19d-4318-8063-41f83fbd6249</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
