<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Best Seller_img-loop lazyloaded</name>
   <tag></tag>
   <elementGuidId>4073aa07-2bd4-41be-82ac-eb41db0fafd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='mso-collection-product']/div/div/div[3]/div[5]/div/div/div/div[2]/a/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-loop.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;WEEKEND MAX MARA - Quần jeans ống rộng phối hoạ tiết hoa Omelia&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a4463e65-bf23-421f-8ad9-1f4581c0959d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2acd47f3-396c-4df9-85ab-272e2a0ebaeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>45702f74-2395-49e3-b796-967a6de0eedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-loop lazyloaded</value>
      <webElementGuid>ceeaad9d-cb66-41ec-9c5d-26d273ae3d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//product.hstatic.net/1000284478/product/13_5181084106_1_72e7a90acdf9402f9607b3b0ff62bdea_large.jpg</value>
      <webElementGuid>8ff6aa14-2676-4a64-be47-3eb92e680043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>//product.hstatic.net/1000284478/product/13_5181084106_1_72e7a90acdf9402f9607b3b0ff62bdea_large.jpg</value>
      <webElementGuid>2891dbe0-a267-4948-a2c3-97d6448058b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>WEEKEND MAX MARA - Quần jeans ống rộng phối hoạ tiết hoa Omelia</value>
      <webElementGuid>bb28c8ca-1501-41f5-ba4a-c572f2254215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mso-collection-product&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;mso-collection-main active&quot;]/div[@class=&quot;mso-collection-right&quot;]/div[@class=&quot;mso-collection-list&quot;]/div[@class=&quot;product-list-collection d-flex flex-wrap&quot;]/div[@class=&quot;jsloop product-loop  label_tag_setting&quot;]/div[@class=&quot;product-loop-inner&quot;]/div[@class=&quot;product-loop-img proloop-image&quot;]/a[1]/picture[@class=&quot;first-image&quot;]/img[@class=&quot;img-loop lazyloaded&quot;]</value>
      <webElementGuid>ea8a4c2a-f161-41ea-8c0b-69e13c250e56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='mso-collection-product']/div/div/div[3]/div[5]/div/div/div/div[2]/a/picture/img</value>
      <webElementGuid>8765401c-fddd-4493-9f35-989e88520994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='WEEKEND MAX MARA - Quần jeans ống rộng phối hoạ tiết hoa Omelia']</value>
      <webElementGuid>a49728e1-5e12-4608-82e2-2632afac25d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/picture/img</value>
      <webElementGuid>c8aeffd9-c75e-4559-b913-214c30cf4f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//product.hstatic.net/1000284478/product/13_5181084106_1_72e7a90acdf9402f9607b3b0ff62bdea_large.jpg' and @alt = 'WEEKEND MAX MARA - Quần jeans ống rộng phối hoạ tiết hoa Omelia']</value>
      <webElementGuid>4f56c8b7-4822-4340-9eb8-12ec8e492ad1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
